import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id "architectury-plugin" version "3.4.164"
    id "dev.architectury.loom" version "1.9-SNAPSHOT"
    id "org.jetbrains.kotlin.jvm" version "2.2.21"

    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

architectury {
    minecraft = project.minecraft_version
    platformSetupLoomIde()
    neoForge {
        platformPackage = "neoforge"
    }
}

loom {
    mods {
        main {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://maven.architectury.dev/" }
    maven { url "https://maven.neoforged.net/releases/" }
    maven { url "https://thedarkcolour.github.io/KotlinForForge/" }
    maven { url "https://maven.theillusivec4.top/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    neoForge "net.neoforged:neoforge:${project.neo_forge_version}"

    compileOnly files("libs/hexcasting-neoforge-${project.minecraft_version}-${project.hexcasting_version}.jar")
    runtimeOnly files("libs/hexcasting-neoforge-${project.minecraft_version}-${project.hexcasting_version}.jar")
    runtimeOnly files("libs/paucal-${project.paucal_version}+${project.minecraft_version}-neoforge.jar")
    runtimeOnly files("libs/inline-${project.minecraft_version}-${project.inline_version}-neoforge-devruntime.jar")
    runtimeOnly files("libs/caelus-neoforge-${project.caelus_version}.jar")
    compileOnly files("libs/Patchouli-1.21.1-93-NEOFORGE.jar")
    runtimeOnly files("libs/Patchouli-1.21.1-93-NEOFORGE.jar")

    compileOnly files("libs/hexpose-neoforge-1.0.0+1.21.1-neoforge-pre39.jar")
    runtimeOnly files("libs/hexpose-neoforge-1.0.0+1.21.1-neoforge-pre39.jar")
    compileOnly files("libs/moreiotas-0.1.1+1.21.1-neoforge-pre39.jar")
    runtimeOnly files("libs/moreiotas-0.1.1+1.21.1-neoforge-pre39.jar")
    compileOnly files("libs/curios-neoforge-9.5.1+1.21.1.jar")
    runtimeOnly files("libs/curios-neoforge-9.5.1+1.21.1.jar")
    compileOnly files("libs/geckolib-neoforge-1.21.1-4.9.2.jar")
    runtimeOnly files("libs/geckolib-neoforge-1.21.1-4.9.2.jar")

    modRuntimeOnly "dev.architectury:architectury-neoforge:${project.architectury_version}"
    modRuntimeOnly "me.shedaniel.cloth:cloth-config-neoforge:15.0.130"
    runtimeOnly "thedarkcolour:kotlinforforge-neoforge:${project.kotlin_for_forge_version}"

    testImplementation platform("org.junit:junit-bom:5.11.4")
    testImplementation "org.junit.jupiter:junit-jupiter"
}

def mainCodeDirs = ["src/main/java", "src/client/java"]
sourceSets {
    main {
        java.srcDirs = mainCodeDirs
        resources.srcDirs = ["src/main/resources", "src/client/resources"]
    }
}
sourceSets.main.kotlin.srcDirs = mainCodeDirs

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "21"
        freeCompilerArgs += ["-Xjvm-default=all"]
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

test {
    useJUnitPlatform()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}
