org.gradle.jvmargs=-Xmx768m -XX:+UseSerialGC -Djava.io.tmpdir=D:/mymod/NEOFORGE_1_21_1_PORT_OUTPUT/.gradle-tmp
org.gradle.parallel=true
loom.mixin.useLegacyMixinAp=false
loom.platform=neoforge
kotlin.stdlib.default.dependency=false
kotlin.compiler.execution.strategy=in-process

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
neo_forge_version=21.1.234

hexcasting_version=0.12.0-devel-pre-39
architectury_version=13.0.11
kotlin_for_forge_version=5.12.0
paucal_version=0.7.1-pre-27
inline_version=1.2.2
caelus_version=7.0.1+1.21.1

mod_version=1.0.8+1.21.1-neoforge-pre39
maven_group=io.github.artynova.mediaworks
archives_base_name=mediaworks-neoforge
